name: C/C++ CI

on: [pull_request, push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild SSE2
      working-directory: GOESP
      run: msbuild GOESP.vcxproj /p:Configuration=Release /p:Platform=Win32 /p:VisualStudioVersion=16.0 /v:m /p:OutDir="D:\a\GOESP\GOESP\GOESP\Release\SSE2\"
    - name: MSBuild AVX
      working-directory: GOESP
      run: msbuild GOESP_AVX.vcxproj /p:Configuration=Release /p:Platform=Win32 /p:VisualStudioVersion=16.0 /v:m /p:OutDir="D:\a\GOESP\GOESP\GOESP\Release\AVX\"
    - name: MSBuild AVX2
      working-directory: GOESP
      run: msbuild GOESP_AVX2.vcxproj /p:Configuration=Release /p:Platform=Win32 /p:VisualStudioVersion=16.0 /v:m /p:OutDir="D:\a\GOESP\GOESP\GOESP\Release\AVX2\"
    - uses: actions/upload-artifact@v1
      with:
        name: Release SSE2
        path: GOESP/Release/SSE2/GOESP.dll
    - uses: actions/upload-artifact@v1
      with:
        name: Release AVX
        path: GOESP/Release/AVX/GOESP_AVX.dll
    - uses: actions/upload-artifact@v1
      with:
        name: Release AVX2
        path: GOESP/Release/AVX2/GOESP_AVX2.dll
